### ISSUE TITLE
Datagen not saved even for 2 game after 1 hour

### ISSUE THREAD

**Issue by Dominic-Purcell** [PGG106/Alexandria#122]
```
HashTable init complete with 1398099 entries
id name Alexandria 4.0-dev
datagen
Starting datagen with 2 threads and an estimated total of 2 games
HashTable init complete with 5592403 entries
Datagen started successfully
```

**Comment by PGG106** [comment]
Datagen needs either a nodes or a depth command, otherwise it default to maxdepth and it's basically unusable, i'll make it so that it straight up cannot be started without the right parameters

**Comment by Dominic-Purcell** [comment]
I'm just trying to help you ...  @PGG106 why did you restrict my account again?  

I followed all the contribution guidelines. Take my chance now or never!

**Comment by PGG106** [comment]
What are you doing is called ban evasion, please abstain from doing so in the future.
