### ISSUE TITLE
Need to use the MultiPV

### ISSUE THREAD

**Issue by chess-com** [PGG106/Alexandria#132]
I need to use MultiPV for search via alpha-beta algorithm. How can I do this?

**Comment by PGG106** [comment]
multiPV isn't currently supported in Alexandria, there are no plans to support it in the near future

**Comment by chess-com** [comment]
https://github.com/PGG106/Alexandria/commit/6921f61bdb4dfc1fea24cefe96868ed212b46a81

Is this commit usable for MultiPV ?

**Comment by PGG106** [comment]
no, as the name says that's a preliminary cleanup done to prepare to implement multipv, in the end multipv was put on indefinite hold, if you need an engine that supports multiPV i'd reccomend using stockfish
