### ISSUE TITLE
error when using SCID

### ISSUE THREAD

**Issue by tissatussa** [PGG106/Alexandria#261]
**Describe the bug**
when using Alexandria in SCID (newest v5.02) it gives this error after starting : _The analysis engine terminated without exit code: ""_

**To Reproduce**
1. add the engine to SCID
2. setup a starting position
3. select Alexandria to analyse that position

**Expected behavior**
the engine should evaluate the position and show its result lines

**Additional context**
this happens with version Alexandria v4.x upto current v5.0.14
NOTE: some other engines, even famous / strong ones, also have this issue : it seems SCID is buggy when handling the (UCI) protocol. When executing SCID by terminal no error is displayed. I'm using Xubuntu 22.04

**Comment by PGG106** [comment]
Hi, testing locally using Scid vs pc version 4.24 works just fine, this is probably a specific problem of Scid v5.02. I'll look for a 5.02 binary to confirm this

**Comment by PGG106** [comment]
Ok i tried Scid 5.02 on windows and after setting up the engine i recieved the same error, however after simply reconfiguring again it appears to work as intended, i'm pretty sure whatever the problem is it's on SCID's end to fix.
![image](https://github.com/PGG106/Alexandria/assets/72303893/1a9c8aeb-25be-4650-b8e9-e2c30a3120fa)

**Comment by PGG106** [comment]
Update: Found the issue, a fix should be published soon

**Comment by tissatussa** [comment]
indeed it's about Scid, not the vs-PC version.
compiling went well and now it runs in Scid !

What did you find (in general terms) ? Did you find Scid not handling the UCI protocol properly ? Is it a timeout issue ? Maybe i can use your finding for other engine authors to be aware and correct their code (many engines fail in Scid here..)

**Comment by PGG106** [comment]
Technically speaking it's not an error on Scid's end, at least it wasn't for me, there are 2 ways to encode startpos with a uci legal command
`position startpos` and `position startpos moves` with no actual moves being appended, Alex assumed that if you were appending the `moves` token were moves to parse, so it tried to parse moves that didn't exist and ended up crashing.
`Position startpos moves` is a legal uci command though, even if unusual.

**Comment by tissatussa** [comment]
OK, thanks.
I know `position startpos moves` is used in polyglot .epd files to set a starting position, it's not unusual, it's an alternative to `position fen [..]` which not all engines understand.

**Comment by PGG106** [comment]
The command itself isn't rare at all, and it's basically a requirement to play any game with any uci GUI. What's unusual is sending the moves token with no moves attached, instead of simply sending position startpos when there are no moves to pass on to the engine.

**Comment by tissatussa** [comment]
now i got you!
a simple fix yes .. nice :-)
