### ISSUE TITLE
Please add ARMv9.2, SVE2, Dot Product and Neon support

### ISSUE THREAD

**Issue by Chess321** [PGG106/Alexandria#378]
It's sad that it's not possible to compile the newest version on Android and Linux devices.

**Comment by cj5716** [comment]
Are you sure? Have you tried running `make` on your device? If there is an error please send it here

**Comment by cj5716** [comment]
we do have a fallback to autovec btw, so just running `make` should work

**Comment by PGG106** [comment]
yeah my bad for missing that among the defines, a native compile on an arm machine should just work, simd targeting neon isn't currently planning, closing this as long as someone doesn't show up with a failed arm compile.
