### ISSUE TITLE
Threads option defined wrong ?

### ISSUE THREAD

**Issue by tissatussa** [PGG106/Alexandria#68]
i successfully compiled your v3.02 source on Linux, Xubuntu 22.04, and it runs fine in CuteChess. Btw. i had no time issue with v3.01, and also v3.02 seems OK.

i see you have a threads option, but it seems wrongly defined :

```
uci
id name Alexandria 3.0.2
id author PGG
option name Hash type spin default 16 min 1 max 8192 
option name Threads type spin default 1 min 1 max 1 
uciok
```

indeed, in CuteChess i can not set threads other then 1 : the min and max are the same ?!

**Comment by PGG106** [comment]
Alexandria currently does not support running with multiple threads, that option is there to suppress a warning from some testing frameworks that expect a thread option from the engine, when alexandria will support running with multiple thread the option will be updated accordingly.

**Comment by PGG106** [comment]
as of now the dev version has support for up to 4 threads (pending further testing)
